/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import acessdata.CategoryDAO;
import acessdata.DataMan;
import accesobj.Category;

import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author samalv
 */
public class DeleteCatUI extends javax.swing.JFrame {

    /**
     * Creates new form DeleteCatUI
     */
    public DeleteCatUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clearButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonEv(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonEv(evt);
            }
        });

        jLabel2.setText("Category");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonEv(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(deleteButton)
                        .addGap(38, 38, 38)
                        .addComponent(clearButton)
                        .addGap(29, 29, 29)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(clearButton)
                    .addComponent(cancelButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonEv(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonEv
        this.nameField.setText("");
    }//GEN-LAST:event_clearButtonEv

    private void cancelButtonEv(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonEv
        this.dispose();
    }//GEN-LAST:event_cancelButtonEv

    private void deleteButtonEv(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonEv
        String name = DataMan.getInstance().getNonNULLStr(this.nameField.getText());

        int value = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete Category?","Delete Category",JOptionPane.YES_NO_OPTION);

        if(value == JOptionPane.YES_OPTION){
            if(name != null){
                try{
                    Category del = DataMan.getInstance().loadCategoryByName(name);

                    if(del != null){
                        DataMan.getInstance().deleteCategory(del);
                        JOptionPane.showMessageDialog(this, "Category deleted succesfully", "!", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(this, "Category not found to delete", "Error!", JOptionPane.ERROR_MESSAGE);
                        throw new IllegalArgumentException("Must have value");
                    }
                }catch(SQLException e){
                    if(e.getSQLState().equals("23000") == true){
                        JOptionPane.showMessageDialog(this, "Can't remove Category that is referenced in other tables \n", "Error!", JOptionPane.ERROR_MESSAGE);

                        System.out.println("Error ... Can't remove Category that is referenced in other tables \n");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);

                        System.out.println("Error ... " + e.getMessage() + "\n");

                    }
                }
            }
        }
    }//GEN-LAST:event_deleteButtonEv


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
