/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import acessdata.ActorDAO;
import acessdata.DataMan;
import accesobj.Actor;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author samalv
 */
public class UpdateActorUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdateActorUI
     */
    public UpdateActorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton1 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        firstNameText = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNameNew = new javax.swing.JTextField();
        lastNameNew = new javax.swing.JTextField();
        newFirst = new javax.swing.JLabel();
        newLast = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        updateButton1.setText("Update");
        updateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonEv(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtoncancelEv(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonclearEv(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        newFirst.setText("New First Name");

        newLast.setText("New Last Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(updateButton1)
                .addGap(66, 66, 66)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(firstNameText)
                        .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newLast)
                    .addComponent(newFirst)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(firstNameNew)
                        .addComponent(lastNameNew, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(newLast)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton1)
                    .addComponent(cancelButton)
                    .addComponent(clearButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtoncancelEv(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtoncancelEv
        this.dispose();
    }//GEN-LAST:event_cancelButtoncancelEv

    private void clearButtonclearEv(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonclearEv
        this.firstNameText.setText("");
        this.lastNameField.setText("");
        this.firstNameNew.setText("");
        this.lastNameNew.setText("");
    }//GEN-LAST:event_clearButtonclearEv

    private void updateButtonEv(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonEv
        String firstName;
        String lastName;
        String newFirst;
        String newLast;
        
        
        firstName = DataMan.getInstance().getNonNULLStr(this.firstNameText.getText());
        lastName = DataMan.getInstance().getNonNULLStr(this.lastNameField.getText());
        newFirst = DataMan.getInstance().getNonNULLStr(this.firstNameNew.getText());
        newLast = DataMan.getInstance().getNonNULLStr(this.lastNameNew.getText());
        
        if(firstName != null && lastName != null && newFirst != null && newLast != null){
            try{
            Actor old = DataMan.getInstance().findActorByFullName(firstName, lastName);
            if(old != null){
                Actor newAct = old;
            
                newAct.setFirstName(newFirst);
                newAct.setLastName(newLast);
            
                DataMan.getInstance().updateActor(newAct);
                JOptionPane.showMessageDialog(this, "Actor updated succesfully", "!", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Actor not found to update", "Error!", JOptionPane.ERROR_MESSAGE);
                throw new IllegalArgumentException("Must have value");
            }
            
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
                System.out.println("Error ... " + e.getMessage() + "\n");

            }
        }
    }//GEN-LAST:event_updateButtonEv


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField firstNameNew;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField lastNameNew;
    private javax.swing.JLabel newFirst;
    private javax.swing.JLabel newLast;
    private javax.swing.JButton updateButton1;
    // End of variables declaration//GEN-END:variables
}
